var pipCanvas = new PipCanvas({
    imgList: [
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
            // gif: 'p1',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
            // gif: 'p4',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
            // gif: 'p6',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
            // gif: 'p7',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
            // gif: 'p9',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
        },
        {
            link: 'img/1.jpg',
            imgW: '1080',
            imgH: '1440',
            areaW: '188',
            areaH: '251',
            areaL: '133',
            areaT: '417',
        },
    ],
    el: '#container',
});
pipCanvas.init();
